### PR TITLE
handle pyyaml just like other dependencies

### PR DESCRIPTION
**Pull request by nabilschear**
first step towards fixing pyyaml dependency stuff.  we'll stick with the distro versions for now.

#81  and eventually will relate to #80

### CODE REVIEW

**Comment by jetwhiz** [comment]
Yeah it looks like they're keeping safe_load around as an alias in 5.1, so it should be safe to use it here.  

It might be good to both lower the min version to 3.12 or 3.11 (ubuntu xenial) and change `yaml.load` to `yaml.safe_load`.  In the future we can plan to integrate OWASP or similar into the CI process so we don't need to worry about checking against min versions anymore.

**Comment by nabilschear** [comment]
So, the installer will already warn on an old version and ask the user for an override.  So, they can proceed.  Do you think we should still have the version check and warning? @lukehinds

**Comment by lukehinds** [comment]
> So, the installer will already warn on an old version and ask the user for an override. So, they can proceed. Do you think we should still have the version check and warning? @lukehinds

Hmm, I personally would not if we use `safe_load`. I say this on basis that a lot of folks might see the warning and out of concern start then trying to use pip or another means of getting a later version of `pyyaml` outside of ubuntu / debians main package repositories and this in turn might bite them later when upgrading etc. I think moving to OS packages over pypi is a good move though and we should definitely keep that code!

**Comment by lukehinds** [comment]
I also wanted to add its highly likely that ubuntu have backported the security fixes into the version in the package repos. 

Red Hat do something similar, they maintain a long term stable version and back port in security fixes. So a version number that is insecure upstream, may well likely be patched for the same release number downstream.

**Comment by lukehinds** [comment]
Here we go: https://launchpad.net/ubuntu/+source/pyyaml/3.11-1ubuntu0.1

**Comment by nabilschear** [comment]
ok, i've left 3.11 in setup.py to make sure that it will just work.  i've removed the check and added the safe_load call.

**Pull request merged**
