### PR TITLE
Add RHEL Family support to demo scripts

### PR DESCRIPTION
**Pull request by lukehinds**
This change adds support for all of the RHEL family for the `demo_setup.sh` and `create_whitelist.sh` scripts.

It closes issues #11 and #12

### CODE REVIEW

**Comment by lukehinds** [comment]
Just realised I need to change from gzip for the rhel conditional in `create_whitelist.sh`

*Please don't merge this yet*

**Comment by nabilschear** [comment]
Thanks!  @jetwhiz should be back working on this by early next week.  We'll make an effort to get this merged soon.  It's been crazy with the holidays.

**Comment by lukehinds** [comment]
> Thanks! @jetwhiz should be back working on this by early next week. We'll make an effort to get this merged soon. It's been crazy with the holidays.

No big rush, its not holding me up.

**Comment by jetwhiz** [comment]
It might be better just to use your version of the create_whitelist.sh, since the version I hacked up a while back (which is conflicting) isn't as thorough as the approach you've taken.

**Comment by jetwhiz** [comment]
@lukehinds go ahead and clobber the existing create_whitelist.sh with your version to resolve the conflict, since I like your solution better.

**Pull request merged**
