### PR TITLE
Warn emulator

### PR DESCRIPTION
**Pull request by nabilschear**
adding a warning to cloud node if using a software tpm emulator #78

### CODE REVIEW

**Comment by lukehinds** [comment]
@jetwhiz , do you see the green 'merge pull request' button, if so feel free to merge as you have been the main reviewer.

**Comment by nabilschear** [comment]
@jetwhiz do you like the warning text?  anything more useful?

**Comment by jetwhiz** [comment]
@nabilschear I think it makes it pretty clear, and stands out in the terminal to bring it to a user's attention.  It might be helpful to add a small note to the main README page urging people not to use the emulated TPMs for production systems.

**Comment by nabilschear** [comment]
yeah, the readme isn't very clear on this.  i'll take a pass over it to emphasize that the emulator is only for testing/debugging purposes.

**Comment by lukehinds** [comment]
@nabilschear do you plan to update the readme in this PR or a new PR (a.k.a should I merge this for you first?)

**Comment by nabilschear** [comment]
@lukehinds i was planning to make a pass over the README in this PR.  then we can merge.

**Comment by lukehinds** [comment]
> @lukehinds i was planning to make a pass over the README in this PR. then we can merge.

Thanks, I will cut a release once we merge this!

**Comment by lukehinds** [comment]
Going to merge this for now, and we can do the readme in another patch! Hope that's ok, I want to get a release out (and readme is not so release dependent).

**Comment by nabilschear** [comment]
no problem.

**Pull request merged**
